In [7]:
import pandas as pd
import numpy as np
import re

In [2]:
comments_df = pd.read_csv('./dataset/comments_sentiment.csv')
comments_df.head(10)

                                            Comments Sentiment
0  oppo indonesia : open recruitment for cmo oppo...   negatif
1                                                NaN   negatif
2                         kelihatan kualitasnya wkwk   negatif
3                               <a href=" <a href="    negatif
4                                             sampah   negatif
5  oppo clearly needs to sign another indonesian ...   negatif
6  wohahahahaha brand hp paling bnyak rusak di ko...   negatif
7   ga pernah tertarik ama smartphone dari brand ini   negatif
8  this is an insult, they think that we are stup...   negatif
9  yaelah kirain terima kritikan malah mencari pe...   negatif

In [12]:
comments_df = comments_df.dropna(subset=['Comments'])
comments_df['Comments'] = comments_df['Comments'].str.replace(r'\byg\b', '', regex=True)
comments_df['Comments'] = comments_df['Comments'].str.replace(r'<a href="[^"]*">[^<]*</a>', '', regex=True)
comments_df.head(10)

                                             Comments Sentiment
0   oppo indonesia : open recruitment for cmo oppo...   negatif
2                          kelihatan kualitasnya wkwk   negatif
3                                <a href=" <a href="    negatif
4                                              sampah   negatif
5   oppo clearly needs to sign another indonesian ...   negatif
6   wohahahahaha brand hp paling bnyak rusak di ko...   negatif
7    ga pernah tertarik ama smartphone dari brand ini   negatif
8   this is an insult, they think that we are stup...   negatif
9   yaelah kirain terima kritikan malah mencari pe...   negatif
10    this video makes me sure not to buy oppo phones   negatif

In [6]:
comments_df.to_csv('./dataset/cleaned_comments.csv', index=False)